import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-1">
        <div className="flex-none lg:w-72">
          <Sidebar />
        </div>
        <div className="w-full">
          <Navbar />
          {children}
        </div>
        </div>
        </body>
    </html>
  );
}
